/*
 * AccesoServidores.java
 *
 * Created on 14 de agosto de 2008, 04:13 PM
 */

package vista;

import control.Ejecutable;
import control.HiloPruebaConexiones;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author  gavarela
 */
public class AccesoServidores extends javax.swing.JFrame {
    private List<String> urlDSpace;
    private List<String> nombresDSpace;
    private List<String> urlOlib;
    private List<String> nombresOlib;
    private List<String> epersonDSpace;
    private List<String> usuariosDSpace;
    private HiloPruebaConexiones hilo;
    
    /** Creates new form AccesoServidores */
    public AccesoServidores(List<String> urlDSpace, List<String> nombresDSpace, List<String> urlOlib, List<String> nombresOlib, List<String> epersonDSpace, List<String> usuariosDSpace) {
        this.urlDSpace = urlDSpace;
        this.nombresDSpace = nombresDSpace;
        this.urlOlib = urlOlib;
        this.nombresOlib = nombresOlib;
        this.epersonDSpace = epersonDSpace;
        this.usuariosDSpace = usuariosDSpace;
        
        initComponents();
        
        //Pone los nombres de las instancias de Olib disponibles
        int contador = 0;
        comboOlib.removeAllItems();
        do{
            comboOlib.addItem(nombresOlib.get(contador));
            contador++;
        }while(contador<nombresOlib.size());
        
        //Pone los nombres de las instancias de DSpace disponibles
        contador = 0;
        comboDSpace.removeAllItems();
        do{
            comboDSpace.addItem(nombresDSpace.get(contador));
            contador++;
        }while(contador<nombresDSpace.size());
        
        //Muestra el servidor a donde se enviarán los archivos, según la instancia de DSpace seleccionada
        if(((String)comboDSpace.getSelectedItem()).equalsIgnoreCase("Repositorio Desarrollo (dspace)")){
            servidorSamba.setText("Desarrollo");            
        }else{
            servidorSamba.setText("Producción");            
        }
        
        
        //Hace aparecer esta ventana en el centro de la pantalla
        this.setLocationRelativeTo(null);
        ayudaCancelar.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDSpace = new javax.swing.JPanel();
        usuarioDSpace = new javax.swing.JTextField();
        labelClaveDSpace = new javax.swing.JLabel();
        labelUsuarioDSpace = new javax.swing.JLabel();
        comboDSpace = new javax.swing.JComboBox();
        labelInstaciaDSpace = new javax.swing.JLabel();
        claveDSpace = new javax.swing.JPasswordField();
        panelOlib = new javax.swing.JPanel();
        usuarioOlib = new javax.swing.JTextField();
        labelUsuarioOlib = new javax.swing.JLabel();
        labelClaveOlib = new javax.swing.JLabel();
        claveOlib = new javax.swing.JPasswordField();
        labelInstaciaOlib = new javax.swing.JLabel();
        comboOlib = new javax.swing.JComboBox();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelSamba = new javax.swing.JPanel();
        usuarioSamba = new javax.swing.JTextField();
        claveSamba = new javax.swing.JPasswordField();
        labelClaveSamba = new javax.swing.JLabel();
        labelUsuarioSamba = new javax.swing.JLabel();
        servidorSamba = new javax.swing.JTextField();
        labelSamba = new javax.swing.JLabel();
        ayudaCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sincronización OLIB-DSpace: Acceso a servidores");
        setName("acessoServidores"); // NOI18N
        setResizable(false);

        panelDSpace.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos de DSpace"));

        usuarioDSpace.setColumns(15);
        usuarioDSpace.setEditable(false);

        labelClaveDSpace.setText("Contraseña:");

        labelUsuarioDSpace.setText("Usuario:");

        comboDSpace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDSpaceActionPerformed(evt);
            }
        });

        labelInstaciaDSpace.setText("Instancia:");

        claveDSpace.setColumns(15);
        claveDSpace.setPreferredSize(new java.awt.Dimension(131, 19));
        claveDSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveDSpaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDSpaceLayout = new javax.swing.GroupLayout(panelDSpace);
        panelDSpace.setLayout(panelDSpaceLayout);
        panelDSpaceLayout.setHorizontalGroup(
            panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDSpaceLayout.createSequentialGroup()
                .addGroup(panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelInstaciaDSpace, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboDSpace, javax.swing.GroupLayout.Alignment.LEADING, 0, 205, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuarioDSpace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClaveDSpace)
                    .addComponent(claveDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDSpaceLayout.setVerticalGroup(
            panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInstaciaDSpace)
                    .addComponent(labelUsuarioDSpace)
                    .addComponent(labelClaveDSpace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claveDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOlib.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos de OLIB"));

        usuarioOlib.setColumns(15);

        labelUsuarioOlib.setText("Usuario:");

        labelClaveOlib.setText("Contraseña:");

        claveOlib.setColumns(15);
        claveOlib.setPreferredSize(new java.awt.Dimension(131, 19));
        claveOlib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveOlibActionPerformed(evt);
            }
        });

        labelInstaciaOlib.setText("Instancia:");

        comboOlib.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelOlibLayout = new javax.swing.GroupLayout(panelOlib);
        panelOlib.setLayout(panelOlibLayout);
        panelOlibLayout.setHorizontalGroup(
            panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOlibLayout.createSequentialGroup()
                .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInstaciaOlib)
                    .addComponent(comboOlib, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioOlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuarioOlib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveOlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClaveOlib))
                .addGap(185, 185, 185))
        );
        panelOlibLayout.setVerticalGroup(
            panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOlibLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOlibLayout.createSequentialGroup()
                        .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUsuarioOlib)
                            .addComponent(labelClaveOlib))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOlibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioOlib, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(claveOlib, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOlibLayout.createSequentialGroup()
                        .addComponent(labelInstaciaOlib)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboOlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        panelSamba.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidor de archivos de DSpace"));

        usuarioSamba.setColumns(15);

        claveSamba.setColumns(15);
        claveSamba.setPreferredSize(new java.awt.Dimension(131, 19));
        claveSamba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveSambaActionPerformed(evt);
            }
        });

        labelClaveSamba.setText("Contraseña:");

        labelUsuarioSamba.setText("Usuario:");

        servidorSamba.setColumns(15);
        servidorSamba.setEditable(false);

        labelSamba.setText("Servidor:");

        javax.swing.GroupLayout panelSambaLayout = new javax.swing.GroupLayout(panelSamba);
        panelSamba.setLayout(panelSambaLayout);
        panelSambaLayout.setHorizontalGroup(
            panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSambaLayout.createSequentialGroup()
                .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servidorSamba, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSamba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioSamba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuarioSamba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveSamba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClaveSamba))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelSambaLayout.setVerticalGroup(
            panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSambaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSambaLayout.createSequentialGroup()
                        .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelClaveSamba)
                            .addComponent(labelUsuarioSamba)
                            .addComponent(labelSamba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSambaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(claveSamba, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioSamba, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(servidorSamba, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ayudaCancelar.setText("La comprobación de datos puede tardar unos minutos, puede terminarla presionando Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ayudaCancelar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar)))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDSpace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSamba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOlib, 0, 491, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSamba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(ayudaCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String conexiónOlib = urlOlib.get(comboOlib.getSelectedIndex());
        String conexiónDSpace = urlDSpace.get(comboDSpace.getSelectedIndex());
        String conexiónSamba;
        if(servidorSamba.getText().equalsIgnoreCase("Desarrollo")){
            conexiónSamba = Ejecutable.getControl().getSambaDesarrollo();
        }else{
            conexiónSamba = Ejecutable.getControl().getSambaProduccion();
        }
        //Este hilo realiza pruebas de conexión a los servidores, puede ser interrumpido presionando Cancelar
        hilo = new HiloPruebaConexiones(usuarioOlib.getText(), claveOlib.getPassword(), conexiónOlib, usuarioDSpace.getText(), claveDSpace.getPassword(), conexiónDSpace, usuarioSamba.getText(), claveSamba.getPassword(), conexiónSamba);
        hilo.start();
        
        botonAceptar.setEnabled(false);
        botonCancelar.setEnabled(true);
        ayudaCancelar.setVisible(true);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        if(hilo.isAlive()){
            hilo.interrupt();
            botonCancelar.setEnabled(false);
            botonAceptar.setEnabled(true);
            ayudaCancelar.setVisible(false);
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboDSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDSpaceActionPerformed
        if (comboDSpace.getSelectedItem() != null) {
            //Pone el usuario adecuado de la Base de Datos
            usuarioDSpace.setText(usuariosDSpace.get(comboDSpace.getSelectedIndex()));
            
            //Muestra el servidor a donde se enviarán los archivos, según la instancia de DSpace seleccionada
            if (((String) comboDSpace.getSelectedItem()).equals("Repositorio Desarrollo (dspace)")) {
                servidorSamba.setText("Desarrollo");
            } else {
                servidorSamba.setText("Producción");
            }
        }
    }//GEN-LAST:event_comboDSpaceActionPerformed

    private void claveOlibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveOlibActionPerformed
        botonAceptarActionPerformed(evt);
    }//GEN-LAST:event_claveOlibActionPerformed

    private void claveDSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveDSpaceActionPerformed
        botonAceptarActionPerformed(evt);
    }//GEN-LAST:event_claveDSpaceActionPerformed

    private void claveSambaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveSambaActionPerformed
        botonAceptarActionPerformed(evt);
    }//GEN-LAST:event_claveSambaActionPerformed

    /*Gavarela: se pasará la excepción para poner en pantalla en mensaje de esta */
    public void errorOlib(/*int código*/String mensaje){
        /*if(código == 1){
            JOptionPane.showMessageDialog(this, "El usuario y la contraseña de la Base de Datos del Olib seleccionado no corresponden", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Existe un problema con el Driver de Oracle, favor comunicarse con soporte de Biblioteca", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }*/
        JOptionPane.showMessageDialog(this, mensaje, "Error de conexión - OLIB", JOptionPane.ERROR_MESSAGE);
        botonCancelar.setEnabled(false);
        botonAceptar.setEnabled(true);
        ayudaCancelar.setVisible(false);
    }

    /*Gavarela: se pasará la excepción para poner en pantalla en mensaje de esta */
    public void errorDSpace(/*int código*/String mensaje){
        /*if(código == 1){
            JOptionPane.showMessageDialog(this, "El usuario y la contraseña de la Base de Datos del DSpace seleccionado no corresponden", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Existe un problema con el Driver de Oracle, favor comunicarse con soporte de Biblioteca", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }*/
        JOptionPane.showMessageDialog(this, mensaje, "Error de conexión - DSpace", JOptionPane.ERROR_MESSAGE);
        botonCancelar.setEnabled(false);
        botonAceptar.setEnabled(true);
        ayudaCancelar.setVisible(false);
    }
    
    public void errorSamba(){
        JOptionPane.showMessageDialog(this, "El usuario y la contraseña del Servidor de archivos del DSpace seleccionado no corresponden", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        botonCancelar.setEnabled(false);
        botonAceptar.setEnabled(true);
        ayudaCancelar.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayudaCancelar;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JPasswordField claveDSpace;
    private javax.swing.JPasswordField claveOlib;
    private javax.swing.JPasswordField claveSamba;
    private javax.swing.JComboBox comboDSpace;
    private javax.swing.JComboBox comboOlib;
    private javax.swing.JLabel labelClaveDSpace;
    private javax.swing.JLabel labelClaveOlib;
    private javax.swing.JLabel labelClaveSamba;
    private javax.swing.JLabel labelInstaciaDSpace;
    private javax.swing.JLabel labelInstaciaOlib;
    private javax.swing.JLabel labelSamba;
    private javax.swing.JLabel labelUsuarioDSpace;
    private javax.swing.JLabel labelUsuarioOlib;
    private javax.swing.JLabel labelUsuarioSamba;
    private javax.swing.JPanel panelDSpace;
    private javax.swing.JPanel panelOlib;
    private javax.swing.JPanel panelSamba;
    private javax.swing.JTextField servidorSamba;
    private javax.swing.JTextField usuarioDSpace;
    private javax.swing.JTextField usuarioOlib;
    private javax.swing.JTextField usuarioSamba;
    // End of variables declaration//GEN-END:variables
}
