/*
 * ColeccionDspace.java
 *
 * Created on 3 de julio de 2007, 02:32 PM
 */

package vista;

import control.Ejecutable;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author  admin
 */
public class ConsultaDspace extends javax.swing.JFrame {
    
    private static String texto;
    private static String usuario;
    private static String contraseña;
    private static String url;
    
    /** Creates new form ColeccionDspace */
    public ConsultaDspace(String usuariox, String contraseñax, String urlx) throws ClassNotFoundException, SQLException{
        usuario = usuariox;
        contraseña= contraseñax;
        url = urlx;
        initComponents();
        //gavarela: por comodidad, la ventana se pone en el centro
        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ClassNotFoundException, SQLException {

        jPanel1 = new javax.swing.JPanel();
        textoClave = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jscrollpane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botonAceptar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Colección en DSPACE");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Colección en DSPACE"));

        textoClave.setToolTipText("Nombre o descripción de la colección");
        textoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClaveActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        Tabla tab = new Tabla(texto,usuario,contraseña,url,"DSPACE");
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla = tab.getTable();
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jscrollpane.setViewportView(tabla);

        org.jdesktop.layout.GroupLayout panelTablaLayout = new org.jdesktop.layout.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jscrollpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jscrollpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonAceptar.setText("Aceptar");
        botonAceptar.setEnabled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(textoClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(botonBuscar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 134, Short.MAX_VALUE)
                .add(botonAceptar)
                .addContainerGap())
            .add(panelTabla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonBuscar)
                    .add(botonAceptar)
                    .add(textoClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelTabla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Temas de ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        botonAceptar.setEnabled(true);
    }//GEN-LAST:event_tablaMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        int fila = tabla.getSelectedRow();
        int columna = tabla.getSelectedColumn();
        if(fila == -1 || columna == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una colección");
        }else{
            if(tabla.getValueAt(fila,columna) == ""){
                JOptionPane.showMessageDialog(this, "Debe seleccionar una colección");
            }else{
                Ejecutable.getControl().getGui().getIdColeccion().setText((String)tabla.getValueAt(fila,0));
                Ejecutable.getControl().getGui().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try {
            texto = textoClave.getText().toLowerCase();
            Tabla tab = new Tabla(texto,usuario,contraseña, url,"DSPACE");
            tabla = tab.getTable();
            tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            this.dispose();
            new ConsultaDspace(usuario, contraseña, url).setVisible(true);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Existe un problema con el driver de ORACLE favor comunicarse con soporte técnico");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión: "+ex.getMessage());
	}
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void textoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClaveActionPerformed
        //gavarela: por comodidad, para que no se tenga que hace clic siempre en el botón.
        botonBuscarActionPerformed(evt);
    }//GEN-LAST:event_textoClaveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultaDspace("","","jdbc:oracle:thin:@200.3.192.29:1521:FILES").setVisible(true);
                } catch (ClassNotFoundException ex) {
			System.err.println("Cannot find the database driver classes.");
			System.err.println(ex);
		} catch (SQLException ex) {
			System.err.println("Cannot connect to this database.");
			System.err.println(ex);
		}
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jscrollpane;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textoClave;
    // End of variables declaration//GEN-END:variables
    
}
